CREATE TABLE MEMBER(
	NAME VARCHAR2(10),
	USERID VARCHAR2(10),
	PWD VARCHAR2(10),
	EMAIL VARCHAR2(20),
	PHONE CHAR(13),
	ADMIN NUMBER(1) DEFAULT 0, -- 0:사용자, 1:관리자
	JOINDATE DATE DEFAULT SYSDATE,
	PRIMARY KEY (USERID)
);

-- NAME 저장공간 20으로 변경
ALTER TABLE MEMBER MODIFY NAME VARCHAR2(20);

SELECT *
  FROM USER_TABLES;

 -- 접속한 계정의 테이블별 제약조건 검색
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'MEMBER';

-- 접속한 계정의 테이블별 컬럼 조회
SELECT *
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'MEMBER';
 
