INSERT ALL INTO MEMBER VALUES('이소미', 'somi', '1234', 'gmd@naver.com', '010-2362-5157', 0, SYSDATE)
	 	   INTO MEMBER VALUES('하상오', 'sang12', '1234', 'ha12@naver.com', '010-5629-8888', 1, SYSDATE)
		   INTO MEMBER VALUES('김윤승', 'light', '1234', 'youn1004@naver.com', '010-9999-8282', 0, SYSDATE)
		   SELECT 1 FROM DUAL;
SELECT NAME, USERID, PWD, EMAIL, PHONE, JOINDATE FROM MEMBER WHERE USERID = 'somi';

SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES(?,?,?,?,?,?,?);

UPDATE MEMBER SET NAME = ?, USERID = ?, PWD = ?, EMAIL = ?, PHONE = ?, ADMIN = ?, JOINDATE = ? WHERE USERID = ?


DELETE FROM MEMBER WHERE USERID = 'gkstjr';